name: Integration tests

on: 
  pull_request:
    types: [reopened, synchronize, labeled, opened]
    branches: ["*"] 
  schedule:
    - cron: '00 2 * * 1-5'
  workflow_dispatch:
    branches: ["*"]

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install CLI
        run: npm i -g @saleor/cli

      - name: run-cypress
        uses: cypress-io/github-action@v4

      - name: Install CLI
         run: npm i saleor-cli

      - name: Cypress run full spec
        uses: cypress-io/github-action@v4
 
          CYPRESS_baseUrl: ${{ secrets.CYPRESS_BASEURL }}
          CYPRESS_USER_NAME: ${{ secrets.CYPRESS_USER_NAME }}
          CYPRESS_SECOND_USER_NAME: ${{ secrets.CYPRESS_SECOND_USER_NAME }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_PERMISSIONS_USERS_PASSWORD: ${{ secrets.CYPRESS_PERMISSIONS_USERS_PASSWORD }}
          CYPRESS_MAILHOG: ${{ secrets.CYPRESS_MAILHOG }}
          COMMIT_INFO_MESSAGE: All tests triggered via ${{ github.event_name}}
  
