name: demo

on: 
  [pull_request]

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install CLI
        run: npm i -g @saleor/cli

      - name: run-cypress
        uses: cypress-io/github-action@v4